# Generated by Django 3.1.3 on 2020-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cartmodel_productsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
